// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaHvFkWSw99AWf9lq_-RVbHjkogB1DZfg',
    appId: '1:927349103773:web:a8b0db5589767ed8f38874',
    messagingSenderId: '927349103773',
    projectId: 'chat-app-be77b',
    authDomain: 'chat-app-be77b.firebaseapp.com',
    storageBucket: 'chat-app-be77b.appspot.com',
    measurementId: 'G-BHKSH3S37C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBad2ycpRp2sMLiEzLxLt_sBFE4Rp9MIsk',
    appId: '1:927349103773:android:0e07d3a46253712af38874',
    messagingSenderId: '927349103773',
    projectId: 'chat-app-be77b',
    storageBucket: 'chat-app-be77b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzOPzom0OtLzYzrjds3Q7uTo8KOzZRwoU',
    appId: '1:927349103773:ios:f01434b3823e4c38f38874',
    messagingSenderId: '927349103773',
    projectId: 'chat-app-be77b',
    storageBucket: 'chat-app-be77b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzOPzom0OtLzYzrjds3Q7uTo8KOzZRwoU',
    appId: '1:927349103773:ios:f01434b3823e4c38f38874',
    messagingSenderId: '927349103773',
    projectId: 'chat-app-be77b',
    storageBucket: 'chat-app-be77b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaHvFkWSw99AWf9lq_-RVbHjkogB1DZfg',
    appId: '1:927349103773:web:526c0bfdde4be97ef38874',
    messagingSenderId: '927349103773',
    projectId: 'chat-app-be77b',
    authDomain: 'chat-app-be77b.firebaseapp.com',
    storageBucket: 'chat-app-be77b.appspot.com',
    measurementId: 'G-70QJ08DNJM',
  );
}
